name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install TexLive (minimal)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-xetex
      
      - name: Compile Ximera to HTML
        run: |
          cd chapters
          # Add your compilation command here
          # Example (adjust based on your setup):
          # for file in *.tex; do pdflatex "$file"; done
          echo "Add your compilation commands here"
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html