name: Compile Ximera

on:
  push:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install TexLive
        run: sudo apt-get install -y texlive-full
      - name: Compile TeX to HTML
        run: |
          # Your compilation commands here
          cd chapters
          # compile tex files to html/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html