name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install make4ht via tlmgr
        run: tlmgr install make4ht
      
      - name: Build with Make
        run: |
          echo "=== Running Make ==="
          make pdf
          make html
          echo "=== Make completed ==="
      
      - name: Check what was created
        run: |
          echo "=== HTML Directory Contents ==="
          ls -lah html/ || echo "HTML directory is empty"
          echo "=== Looking for .html files ==="
          find . -name "*.html" -type f
          echo "=== Looking for .pdf files ==="
          find . -name "*.pdf" -type f
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html