name: Build and Deploy with Xake

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ximeraproject/xake2024:v2.4.2
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure git
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Fix git ownership
        run: |
          chown -R $(whoami) .git
          ls -la .git
      
      - name: Make scripts executable
        run: chmod +x xmScripts/xmlatex*
      
      - name: Build with xake (bake)
        run: |
          pwd
          ls -la
          xake -r . --skip-mathjax bake
      
      - name: Check what was created
        run: |
          echo "=== Checking for HTML files ==="
          find . -name "*.html" -type f | head -20
          echo "=== Checking for PDF files ==="
          find . -name "*.pdf" -type f | head -20
      
      - name: Copy build output to html directory
        run: |
          mkdir -p html
          # Copy all generated HTML files to html directory
          find . -name "*.html" -type f ! -path "./html/*" -exec cp {} html/ \;
          # Copy any generated PDFs
          find . -name "*.pdf" -type f ! -path "./html/*" -exec cp {} html/ \;
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html