name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install make4ht
        run: apt-get update && apt-get install -y make4ht
      
      - name: Build with Make
        run: make all
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html