name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Check repository structure
        run: ls -la
      
      - name: Compile Ximera to HTML
        run: |
          # Add your compilation command here
          # Adjust the path based on where your .tex files are located
          echo "Add your compilation commands here"
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html