name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install TexLive
        run: sudo apt-get install -y texlive-full
      
      - name: Compile Ximera to HTML
        run: |
          cd chapters
          # Your compilation command here
          # Example: latexmk -pdf *.tex (adjust as needed)
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html